name: Docker and Helm

on:
  release:
    types: [published]
  workflow_dispatch:
  
jobs:
  dockerbuild:
    uses: eclipse-xfsc/dev-ops/.github/workflows/dockerbuild.yml@main
    with: 
      harbor_config: "deployment/harbor.config"
      dockerfile: "deployment/docker/Dockerfile"